### PR TITLE
ntfy.sh support

### PR DESCRIPTION
**Pull request by simonpacis**
As an alternative to Twilio SMS, ntfy.sh allows you to send push notifications to iOS and Android free of charge. To use this, simply enter your ntfy.sh-channel in config.json.

### CODE REVIEW

**Comment by John3356** [comment]
Hello I need to get an auto clicker for amazon flex please . Thanks my phone number is +14708383125

**Comment by simonpacis** [comment]
Hi,

That is what this is.

**Comment by simonpacis** [comment]
Hi John,

This repository is an auto clicker, however, what you've commented on is a pull request for adding a feature to Amazon Flex Unlimited. Go to the base repository and follow the instructions to use the script.

**Comment by John3356** [comment]
Hi how are you? please can you contact me my phone number is +14708383125

**Pull request closed without merging**
